name: Format

on:
  schedule:
    - cron: 0,10,20,30,50,59 3 * * 3,5 # At minute 0, 10, 20, 30, 50, and 59 past hour 8 on Wednesday and Friday.

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          # Recommended if you use MacOS:
          # github-token: ${{ secrets.GITHUB_TOKEN }}

permissions: write-all
